import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const publicDir = path.join(root, 'public');
const siteUrl = (process.env.SITE_URL || '').replace(/\/$/, '');
const esc = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const abs = route => siteUrl ? `${siteUrl}${route}` : route;
const strip = html => html.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
async function walk(dir){const out=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){if(e.name==='source'||e.name==='dist')continue;const f=path.join(dir,e.name);if(e.isDirectory())out.push(...await walk(f));else if(e.isFile()&&e.name==='index.html')out.push(f)}return out}
const files=await walk(publicDir);
for(const file of files){let html=await fs.readFile(file,'utf8');const rel=path.relative(publicDir,file).replaceAll(path.sep,'/');const route=rel==='index.html'?'/':`/${rel.slice(0,-'/index.html'.length)}/`;const title=strip(html.match(/<title>([\s\S]*?)<\/title>/i)?.[1]||'LLM به زبان آدمیزاد');const description=strip(html.match(/<meta\s+name="description"\s+content="([\s\S]*?)"/i)?.[1]||'راهنمای فارسی و کاربردی برای یادگیری و استفاده از مدل‌های زبانی بزرگ (LLM).');const canonical=abs(route);const isHome=route==='/';const isAbout=route==='/about/';const type=isHome?'WebSite':isAbout?'AboutPage':'Article';const schemas=[];schemas.push(isHome?{'@context':'https://schema.org','@type':'WebSite','name':'LLM به زبان آدمیزاد','url':canonical,'description':description,'inLanguage':'fa-IR','publisher':{'@type':'Organization','name':'LLM به زبان آدمیزاد'}}:isAbout?{'@context':'https://schema.org','@type':'AboutPage','name':title,'url':canonical,'description':description,'inLanguage':'fa-IR','isPartOf':{'@type':'WebSite','name':'LLM به زبان آدمیزاد','url':abs('/')},'publisher':{'@type':'Organization','name':'LLM به زبان آدمیزاد'}}:{'@context':'https://schema.org','@type':'Article','headline':title,'name':title,'description':description,'url':canonical,'mainEntityOfPage':{'@type':'WebPage','@id':canonical},'inLanguage':'fa-IR','author':{'@type':'Organization','name':'LLM به زبان آدمیزاد'},'publisher':{'@type':'Organization','name':'LLM به زبان آدمیزاد'},'isPartOf':{'@type':'WebSite','name':'LLM به زبان آدمیزاد','url':abs('/')}});if(!isHome){schemas.push({'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'خانه','item':abs('/')},{'@type':'ListItem','position':2,'name':title,'item':canonical}]})}const meta=`<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"><meta name="author" content="LLM به زبان آدمیزاد"><meta name="language" content="fa-IR"><meta name="theme-color" content="#0a0a0a"><link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="${isHome?'website':'article'}"><meta property="og:locale" content="fa_IR"><meta property="og:site_name" content="LLM به زبان آدمیزاد"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(canonical)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}">${schemas.map(s=>`<script type="application/ld+json">${JSON.stringify(s)}</script>`).join('')}`;if(!html.includes('<link rel="canonical"'))html=html.replace('</head>',`${meta}</head>`);await fs.writeFile(file,html)}
const routes=files.map(f=>{const r=path.relative(publicDir,f).replaceAll(path.sep,'/');return r==='index.html'?'/':`/${r.slice(0,-'/index.html'.length)}/`}).sort();await fs.writeFile(path.join(publicDir,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(r=>`<url><loc>${esc(abs(r))}</loc></url>`).join('')}</urlset>`);await fs.writeFile(path.join(publicDir,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${abs('/sitemap.xml')}\n`);console.log(`SEO metadata generated for ${files.length} pages.`);
